### PR TITLE
Please take my amazing code

### PR DESCRIPTION
**Pull request by JamesApple**
Thanks

### CODE REVIEW

**Comment by JamesApple** [comment]
Please

**Comment by mjbamford** [comment]
👍 💯

**Comment by JamesApple** [comment]
Thanks mate

**Comment by andresrgallo** [comment]
👍

**Comment by casscass** [comment]
👍

**Comment by rhyswoodberry** [comment]
💯 💯 💯

**Comment by cryptohashhash** [comment]
👍 👎

**Comment by BestLuke** [comment]
👎 👎

**Comment by ChristopherForrest** [comment]
🥇

**Comment by samfoong** [comment]
👍

**Comment by BestLuke** [comment]
ÒÓ
 < >

**Comment by Andrew-CC-Martin** [comment]
:sparkling_heart:  :sparkling_heart: :sparkling_heart: :sparkling_heart:

**Pull request merged**
